# Generated by Django 4.0.3 on 2022-03-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
