# Generated by Django 4.0.3 on 2022-03-18 13:56

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=payments.models.generate_coupon_code, editable=False, max_length=15),
        ),
    ]
