# Generated by Django 4.0.3 on 2022-03-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_category_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
    ]
