# Generated by Django 4.0.3 on 2022-03-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_discount'),
        ('api', '0013_discount_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.discount'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
