# Generated by Django 4.0.3 on 2022-03-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
