# Generated by Django 4.0.3 on 2022-03-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, default='smth', unique=True),
            preserve_default=False,
        ),
    ]
