# Generated by Django 4.0.3 on 2022-03-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
